books/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'books'

urlpatterns = [
    path('', views.BooksModelView.as_view(), name='index'),
    path('book/', views.BookList.as_view(), name='book_list'),
    path('author/', views.AuthorList.as_view(), name='author_list'),
    path('publisher/', views.PublisherList.as_view(), name='publisher_list'),
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path('author/<int:pk>/', views.AuthorDetail.as_view(), name='author_detail'),
    path('publisher/<int:pk>/', views.PublisherDetail.as_view(), name='publisher_detail'),
]

django_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("minipjs.urls")),
    path('polls/', include("polls.urls")),
    path('yes24/', include("yes24.urls")),
    path('books/', include("books.urls")),
]

minipjs/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'minipjs'

urlpatterns = [
    # path('', views.main, name='main'),
    path('', TemplateView.as_view(template_name='main.html'), name='main'),
    path('calculator', views.calculator, name='calculator'),
    path('naver_book', views.naver_book, name='naver_book'),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
from django.db import models
# from .validators import validate_com

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
    

# class Contact(models.Model):
#     subject = models.CharField(max_length=100)
#     message = models.CharField(max_length=200)
#     sender = models.EmailField(validators=[validate_com])
#     cc_myself = models.BooleanField(black=True, null=True)

polls/forms.py
from django.forms import ModelForm
from .models import Contact

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['subject','message','sender']
        # exclude = ['cc_myself']
        # fields = '__all__'

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from polls.models import Question, Choice

def index(request):
    latest_question_list = Question.objects.all().order_by('-pub_date')[:5]
    context = {'latest_question_list' : latest_question_list}
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question' : question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # 설문 투표 폼을 다시 보여준다.
        return render(request, 'polls/detail.html',
                      {'question' : question, 'error_message' : "You didn't select a choice.",})
    else:
        selected_choice.votes +=1
        selected_choice.save()
        # POST 데이터를 정상적으로 처리하였으면,
        # 항상 HttpResponseRedirect를 반환하여 리다이렉션 처리함
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question' : question})

templates/polls/detail.html
<form action="{% url 'polls:vote' question.pk %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{question.question_text}}</h1></legend>
        {% if erroor_message %}<p><strong>{{erroor_message}}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
            <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label>
            <br>            
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

<a href="{% url 'minipjs:main' %}">Main으로 돌아가기</a>

templates/polls/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li>
                <a href="/polls/{{question.id}}/">{{question.question_text}}</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<a href="{% url 'minipjs:main' %}">Main으로 돌아가기</a>

templates/polls/results.html
<h1>{{question.question_text}}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

<a href="{% url 'minipjs:main' %}">Main으로 돌아가기</a>