books/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'books'

urlpatterns = [
    path('', views.BooksModelView.as_view(), name='index'),
    path('book/', views.BookList.as_view(), name='book_list'),
    path('author/', views.AuthorList.as_view(), name='author_list'),
    path('publisher/', views.PublisherList.as_view(), name='publisher_list'),
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path('author/<int:pk>/', views.AuthorDetail.as_view(), name='author_detail'),
    path('publisher/<int:pk>/', views.PublisherDetail.as_view(), name='publisher_detail'),
]

django_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("minipjs.urls")),
    path('polls/', include("polls.urls")),
    path('yes24/', include("yes24.urls")),
    path('books/', include("books.urls")),
]

books/models.py
from django.db import models

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField('Author')
    publisher = models.ForeignKey('Publisher', on_delete=models.CASCADE)
    publication_date = models.DateField()

    def __str__(self):
        return self.title

class Author(models.Model):
    salutation = models.CharField(max_length=100)
    name = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return self.name


class Publisher(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    website = models.URLField()

    def __str__(self):
        return self.name

books/views.py
from typing import Any
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic import ListView
from django.views.generic import DetailView
from books.models import Book, Author, Publisher

# TemplateView
class BooksModelView(TemplateView):
    template_name = 'books/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['model_list'] = ['Book', 'Author', 'Publisher']
        return context
    
# ListView
class BookList(ListView):
    model = Book

class AuthorList(ListView):
    model = Author

class PublisherList(ListView):
    model = Publisher

# DetailView
class BookDetail(DetailView):
    model = Book

class AuthorDetail(DetailView):
    model = Author

class PublisherDetail(DetailView):
    model = Publisher

templates/books/author_detail.html
{% extends "base_books.html" %}

{% block content %}
    <h1>{{object.name}}</h1>
    <br>
    <ul>
        <li>{{object.salutation}}</li>
        <li>Email: {{object.email}}</li>
    </ul>
{% endblock content %}

templates/books/author_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Author List</h2>
    <ul>
        {% for author in object_list %}
            <li>
                <a href="{% url 'books:author_detail' author.id %}">{{author.name}}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/books/book_detail.html
{% extends "base_books.html" %}

{% block content %}
    <h1>{{object.title}}</h1>
    <br>
    <ul>
        <li>Authors:
            {% for author in object.authors.all %}
                {{author}}
                {% if not forloop.last %}, {% else %} {% endif %}
            {% endfor %}
        </li>
        <li>Publisher: {{object.publisher}}</li>
        <li>Publication date: {{object.publication_date}}</li>
    </ul>
{% endblock content %}

templates/books/book_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Book List</h2>
    <ul>
        {% for book in object_list %}
            <li>
                <a href="{% url 'books:book_detail' book.id %}">{{book.title}}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/books/index.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Books Management System</h2>
    <ul>
        {% for modelname in model_list %}
            {% with "books:"|add:modelname|lower|add:"_list" as urlvar %}
                <li>
                    <a href="{% url urlvar %}">{{modelname}}</a>
                </li>
            {% endwith %}
        {% endfor %}
    </ul>
{% endblock content %}

templates/books/publisher_detail.html
{% extends "base_books.html" %}

{% block content %}
    <h1>{{object.name}}</h1>
    <br>
    <ul>
        <li>{{object.website}}</li>
        <li>Address: {{object.address}}</li>
    </ul>
{% endblock content %}

templates/books/publisher_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Publisher List</h2>
    <ul>
        {% for publisher in object_list %}
            <li>
                <a href="{% url 'books:publisher_detail' publisher.id %}">{{publisher.name}}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock content %}