books/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'books'

urlpatterns = [
    path('', views.BooksModelView.as_view(), name='index'),
    path('book/', views.BookList.as_view(), name='book_list'),
    path('author/', views.AuthorList.as_view(), name='author_list'),
    path('publisher/', views.PublisherList.as_view(), name='publisher_list'),
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path('author/<int:pk>/', views.AuthorDetail.as_view(), name='author_detail'),
    path('publisher/<int:pk>/', views.PublisherDetail.as_view(), name='publisher_detail'),
]

django_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("minipjs.urls")),
    path('polls/', include("polls.urls")),
    path('yes24/', include("yes24.urls")),
    path('books/', include("books.urls")),
]

minipjs/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'minipjs'

urlpatterns = [
    # path('', views.main, name='main'),
    path('', TemplateView.as_view(template_name='main.html'), name='main'),
    path('calculator', views.calculator, name='calculator'),
    path('naver_book', views.naver_book, name='naver_book'),
]

templates/calc/calculator.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>calc_from.html</title>
</head>
<body>
<h1> 사칙연산 프로그램 Django </h1>
<form action="{% url 'minipjs:calculator' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="num1">
    <select name="oper">
        <option value="+">+</option>
        <option value="-">-</option>
        <option value="*">*</option>
        <option value="/">/</option>
    </select>
    <input type="text" name="num2">
    <input type="submit" value="계산하기">

</form>


<p> 계산 결과: {{num1}}{{oper}}{{num2}} = {{result}} </p>

<a href="{% url 'minipjs:main' %}">Main으로 돌아가기</a>

</body>
</html>