books/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'books'

urlpatterns = [
    path('', views.BooksModelView.as_view(), name='index'),
    path('book/', views.BookList.as_view(), name='book_list'),
    path('author/', views.AuthorList.as_view(), name='author_list'),
    path('publisher/', views.PublisherList.as_view(), name='publisher_list'),
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path('author/<int:pk>/', views.AuthorDetail.as_view(), name='author_detail'),
    path('publisher/<int:pk>/', views.PublisherDetail.as_view(), name='publisher_detail'),
]

django_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("minipjs.urls")),
    path('polls/', include("polls.urls")),
    path('yes24/', include("yes24.urls")),
    path('books/', include("books.urls")),
]

minipjs/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'minipjs'

urlpatterns = [
    # path('', views.main, name='main'),
    path('', TemplateView.as_view(template_name='main.html'), name='main'),
    path('calculator', views.calculator, name='calculator'),
    path('naver_book', views.naver_book, name='naver_book'),
]

yes24/urls.py
from django.urls import path
from . import views

app_name = 'yes24'

urlpatterns = [
    path('', views.yes24index, name='yes24index'),
    path('book_detail/<str:book_id>/', views.BestDetailView.as_view(), name='book_detail'),
    # path('<int:question_id>/results/', views.results, name='results'),
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

yes24/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Yes24Bestlist(models.Model):
    index = models.BigIntegerField(blank=True, null=True)
    book_id = models.TextField(primary_key=True)
    yy = models.BigIntegerField(blank=True, null=True)
    mon = models.BigIntegerField(blank=True, null=True)
    title_h = models.TextField(blank=True, null=True)
    title_m = models.TextField(blank=True, null=True)
    title_e = models.TextField(blank=True, null=True)
    author = models.TextField(blank=True, null=True)
    publisher = models.TextField(blank=True, null=True)
    pub_date = models.TextField(blank=True, null=True)
    price = models.TextField(blank=True, null=True)
    rating = models.FloatField(blank=True, null=True)
    page = models.TextField(blank=True, null=True)
    weight = models.TextField(blank=True, null=True)
    size = models.TextField(blank=True, null=True)
    category = models.TextField(blank=True, null=True)
    pub_book_intro = models.TextField(blank=True, null=True)
    tags = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'yes24bestlist'

yes24/views.py
from django.shortcuts import render
import os
from glob import glob
import random
from django.conf import settings
from django.views.generic.base import TemplateView
from django.views.generic import ListView
from django.views.generic import DetailView
from .models import Yes24Bestlist
import re
from .book_recommand import *

pattern = re.compile(r'\d+')

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
print(BASE_DIR)
img_dir = os.path.join(BASE_DIR, 'static', 'yes24')

def yes24index(request):
    
    # glob을 사용하여 jpg 파일을 모두 가져옴
    book_cover_list = glob(os.path.join(img_dir, 'book_img/*.jpg'))
    # list로 변환
    book_cover_list = list(book_cover_list)
    # print(book_cover_list)
    covers_10 = []
    
    for i in range(10):
        num = random.randrange(len(book_cover_list))
        img_url = book_cover_list[num].split("\\")[-1]
        img_no = re.findall(pattern, img_url)
        print(img_no[0])
        covers_10.append((img_url, img_no[0]))
    
    print(covers_10)
    context = {'covers_10' : covers_10, }
    
    return render(request, 'yes24/yes24index.html', context)

class BestDetailView(DetailView):
    model = Yes24Bestlist
    template_name = 'yes24/book_detail.html'  # 템플릿 파일의 경로
    context_object_name = 'book'
    pk_url_kwarg = 'book_id'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cover_name'] = self.request.GET.get('cover_name', '')
        
        input_book_id = self.kwargs.get(self.pk_url_kwarg)
        recommendations = get_recommendations(input_book_id)
        context['recommendations'] = recommendations

        print(f"입력한 도서 '{input_book_id}'와 유사한 도서 {len(recommendations)}개:")
        for i, book_title in enumerate(recommendations):
            print(f"{i + 1}. {book_title}")

        return context

      

templates/yes24/book_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'yes24/css/book.css' %}">
    
    <title>{{ book.title_h }}</title>
</head>

<body class="detail_body">
    {% if book.title_f != None and book.title_e != None %}
        <h1>&#91;{{book.title_h}}&#93; {{book.title_f}}{{book.title_m}}</h1>
        <h3>{{book.title_e}}</h3>
    {% elif book.title_f != None and book.title_e == None %}
        <h3>{{book.title_f}}</h3>
        <h1>&#91;{{book.title_h}}&#93; {{book.title_m}}</h1>
    {% elif book.title_f == None and book.title_e != None %}
        <h1>&#91;{{book.title_h}}&#93; {{book.title_m}}</h1>
        <h3>{{book.title_e}}</h3>
    {% elif book.title_f == None and book.title_e == None %}
        <h1>&#91;{{book.title_h}}&#93; {{book.title_m}}</h1>
    {% endif %}

    <div class="book_detail_grid-container">
        <!-- 좌측에 이미지 표시 -->
        <div class="book_detail_grid-item">
            <img class="img_detail_page" src="{% static 'yes24/book_img/'|add:cover_name %}" alt="{{cover_name}}">
        </div>

        <!-- 우측에 정보 표시 -->
        <div class="book_detail_grid-item info">
            <!-- 추가 정보 -->
            <p>작가: {{ book.author }}</p>
            <p>출판사: {{ book.publisher }}</p>
            <p>출간일: {{ book.pub_date }}</p>
            <p>가격: {{ book.price }}</p>
            <p>페이지: {{ book.page }}</p>
            <p>무게: {{ book.weight }}</p>
            <p>크기: {{ book.size }}</p>
            <p>리뷰수: {{ book.n_reviews }}</p>
            <p>평점: {{ book.rating }}</p>
            <p>카테고리: {{ book.category }}</p>
            <p>tags: {{ book.tags }}</p>
        </div>

        <!-- 하단에 책 소개 -->
        <div class="book_detail_grid-item introduction" colspan="2">
            <p>책 소개: {{book.pub_book_intro}}</p>
        </div>
        
    </div>

    <hr>

        <h3>유사 카테고리 추천 도서</h3>
    
    <div class="outer-container">
    {% for item in recommendations %}
        <div class="inner-container">
          <img class="recommand" src="{% static 'yes24/book_img/' %}{{ 'bcober_'|add:item|add:'.jpg' }}" alt="{{ 'bcober_'|add:item|add:'.jpg' }}">
        </div>
    {% endfor %}
    </div>
    

    <br>
    <a href="{% url 'minipjs:main' %}">Main으로 돌아가기</a>
</body>

</html>

templates/yes24/yes24index copy 2.html
<!DOCTYPE html>
<html lang="ko">

<head>
    {% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'yes24/css/book.css' %}">
    
    <title>Book Recommandation</title>
</head>

<body>
   
    <h1>장르 및 태그 기반 책 추천 시스템</h1>
    
    <h3>아래의 책 중 하나를 선택하세요</h3>
           
    <div class="grid-container">
        {% for cover_name, cover_no in covers_10 %}
            <div class="grid-item">
                <div class="grid-item">
                    <a href="#" onclick="submitForm('{{cover_no}}', '{{cover_name}}')">
                        <img class="coverimg" src="{% static 'yes24/book_img/'|add:cover_name %}" alt="{{cover_name}}">
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
    
    <script>
        function submitForm(bookId, coverName) {
            var form = document.createElement('form');
            form.action = "{% url 'yes24:book_detail' book_id='dummy' %}".replace('dummy', bookId);
            form.method = "GET";
    
            var inputBookId = document.createElement('input');
            inputBookId.type = 'hidden';
            inputBookId.name = 'book_id';
            inputBookId.value = bookId;
    
            var inputCoverName = document.createElement('input');
            inputCoverName.type = 'hidden';
            inputCoverName.name = 'cover_name';
            inputCoverName.value = coverName;
    
            form.appendChild(inputBookId);
            form.appendChild(inputCoverName);
    
            document.body.appendChild(form);
            form.submit();
        }
    </script>
    
    
   
    <a href="{% url 'minipjs:main' %}">Main으로 돌아가기</a>
    
</body>

</html>

templates/yes24/yes24index copy.html
<!DOCTYPE html>
<html lang="ko">

<head>
    {% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'yes24/css/book.css' %}">
    
    <title>Book Recommandation</title>
</head>

<body>
   
    <h1>장르 및 태그 기반 책 추천 시스템</h1>
    
    <h3>아래의 책 중 하나를 선택하세요</h3>
           
    <div class="grid-container">
        {% for cover_name, cover_no in covers_10 %}
        <div class="grid-item">
            <div class="grid-item">
                <form action="{% url 'yes24:book_detail' book_id=cover_no %}" method="GET">
                    {% csrf_token %}
                    <input type='hidden' name='book_id' value="{{cover_no}}">
                    <input type='hidden' name='cover_name' value="{{cover_name}}">
                    <input type='image' class="coverimg" src="{% static 'yes24/book_img/'|add:cover_name %}" alt="{{cover_name}}">
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
    
    <script>
        function submitForm(formId) {
            document.getElementById(formId).submit();
        }
    </script>
   
    <a href="{% url 'minipjs:main' %}">Main으로 돌아가기</a>
    
</body>

</html>

templates/yes24/yes24index.html
<!DOCTYPE html>
<html lang="ko">

<head>
    {% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'yes24/css/book.css' %}">
    
    <title>Book Recommandation</title>
</head>

<body>
   
    <h1>장르 및 태그 기반 책 추천 시스템</h1>
    
    <h3>아래의 책 중 하나를 선택하세요</h3>
           
    <div class="grid-container">

        {% for cover in covers_10 %}
        <div class="grid-item">
            <form action="{% url 'yes24:yes24index' %}" method="POST" enctype="application/x-www-form-urlencoded">
                {% csrf_token %}
                <input type='hidden' name='book_id' value="{{cover}}">
                <input type='image' class="coverimg" src="{% static 'yes24/book_img/'|add:cover %}" alt="{{cover}}">
            </form>
        </div>
        {% endfor %}
    </div>
   
    <a href="{% url 'minipjs:main' %}">Main으로 돌아가기</a>
    
</body>

</html>